// -------------------------------------
// IMPORTS & APP SETUP
// -------------------------------------
const express = require("express");
const axios = require("axios");
const cors = require("cors");
const bodyParser = require("body-parser");

const app = express();
const PORT = 3001;

app.use(cors({ origin: ["http://localhost:3000", "http://localhost:3002"], credentials: true }));
app.use(bodyParser.json());

// Log incoming requests
app.use((req, res, next) => {
  console.log(`[Backend] ${req.method} ${req.path} - Headers: ${JSON.stringify(req.headers)}`);
  next();
});

// -------------------------------------
// BASE URL & AUTH HEADER BUILDER
// -------------------------------------
const BASE_URL = "https://stage-api.irisgst.com";
const authHeaders = (req) => ({
  "X-Auth-Token": req.headers["x-auth-token"] || req.headers["authorization"]?.replace("Bearer ", "") || "",
  companyId: req.headers["companyid"] || req.headers["companyId"] || "",
  product: req.headers["product"] || "",
});

// -------------------------------------
// UNIVERSAL PROXY HANDLER
// -------------------------------------
async function proxyRequest(res, requestFn) {
  try {
    const response = await requestFn();
    res.json(response.data);
  } catch (error) {
    console.error("[Proxy Error]", error.message, error.response?.data);
    res.status(error?.response?.status || 500).json(error?.response?.data || { error: "Proxy Server Error" });
  }
}

/* ======================================================================
   1. AUTHENTICATION MODULE
   ====================================================================== */
// LOGIN
app.post("/proxy/login", (req, res) =>
  proxyRequest(res, () =>
    axios.post(`${BASE_URL}/irisgst/mgmt/login`, req.body, { headers: { "Content-Type": "application/json", Accept: "application/json" } })
  )
);

// CHANGE PASSWORD
app.post("/proxy/change-password", (req, res) =>
  proxyRequest(res, () =>
    axios.post(
      `${BASE_URL}/irisgst/mgmt/public/user/changepassword`,
      req.body,
      {
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
        },
      }
    )
  )
);
;

/* ======================================================================
   2. EWAYBILL CORE (TOPAZ)
   ====================================================================== */
// Generate EWB
app.post("/proxy/topaz/ewb/generate", (req, res) =>
  proxyRequest(res, () =>
    axios.post(`${BASE_URL}/irisgst/topaz/api/v0.3/ewb`, req.body, { headers: { "Content-Type": "application/json", Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

// Get EWB Details
app.get("/proxy/topaz/ewb/details", (req, res) =>
  proxyRequest(res, () =>
    axios.get(`${BASE_URL}/irisgst/topaz/api/v0.3/getewb/ewbDetails`, { params: req.query, headers: { Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

// Fetch EWB by Number (NIC)
app.get("/proxy/topaz/ewb/byNumber", (req, res) =>
  proxyRequest(res, () =>
    axios.get(`${BASE_URL}/irisgst/topaz/api/v0.3/getewb/ewbNo`, { params: req.query, headers: { Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

/* ======================================================================
   3. EWB ACTIONS
   ====================================================================== */
// Update / Cancel / Reject / Extend
app.put("/proxy/topaz/ewb/action", (req, res) =>
  proxyRequest(res, () =>
    axios.put(`${BASE_URL}/irisgst/topaz/api/v0.3/ewb`, req.body, { headers: { "Content-Type": "application/json", Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

// Update Transporter
app.post("/proxy/topaz/ewb/updateTransporter", (req, res) =>
  proxyRequest(res, () =>
    axios.post(`${BASE_URL}/irisgst/topaz/api/v0.3/transporter`, req.body, { headers: { "Content-Type": "application/json", Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

/* ======================================================================
   4. FETCH EWAYBILL
   ====================================================================== */
// FETCH EWB GENERATED BY DATE
// ======================
// TOPAZ FETCH EWAYBILL BY DATE
// ======================
app.get("/proxy/topaz/ewb/fetchByDate", async (req, res) => {
  try {
    // 1) LOG HEADERS RECEIVED FROM REACT
    console.log("---- Incoming Headers From React ----");
    console.log(req.headers);

    // 2) READ TOKEN + COMPANY ID FROM INCOMING REQUEST
    const token = req.headers["x-auth-token"];
    const companyId = req.headers["companyid"];

    console.log("Extracted Token:", token);
    console.log("Extracted Company ID:", companyId);

    if (!token || !companyId) {
      return res.status(400).json({
        error: "Missing X-Auth-Token or companyId in client request",
      });
    }

    // 3) BUILD FINAL HEADERS SENT TO IRIS
    const finalHeaders = {
      Accept: "application/json",
      product: "TOPAZ",
      "X-Auth-Token": token,
      companyId: companyId,
    };

    // LOG HEADERS GOING TO IRIS GST
    console.log("---- Forwarding Headers To IRIS ----");
    console.log(finalHeaders);

    // 4) PROXY REQUEST TO IRISGST API
    const irisResponse = await axios.get(
      `${BASE_URL}/irisgst/topaz/api/v0.3/getewb/generatorEwbs`,
      {
        params: req.query,
        headers: finalHeaders,
      }
    );

    // 5) SEND BACK RESPONSE
    res.json(irisResponse.data);
  } catch (error) {
    console.error("Fetch EWB Error =>", error.response?.data || error.message);

    res.status(error.response?.status || 500).json(
      error.response?.data || {
        status: 500,
        message: "Internal Server Error",
      }
    );
  }
});




app.get("/proxy/topaz/ewb/fetchOther", (req, res) =>
  proxyRequest(res, () =>
    axios.get(`${BASE_URL}/irisgst/topaz/api/v0.3/getewb/other`, { params: req.query, headers: { Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

app.get("/proxy/topaz/ewb/fetchTransporter", (req, res) =>
  proxyRequest(res, () =>
    axios.get(`${BASE_URL}/irisgst/topaz/api/v0.3/getewb/transporter`, { params: req.query, headers: { Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

/* ======================================================================
   5. CONSOLIDATE EWB
   ====================================================================== */
app.post("/proxy/topaz/cewb/generate", (req, res) =>
  proxyRequest(res, () =>
    axios.post(`${BASE_URL}/irisgst/topaz/api/v0.3/cewb`, req.body, { headers: { "Content-Type": "application/json", Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

app.get("/proxy/topaz/cewb/details", (req, res) =>
  proxyRequest(res, () =>
    axios.get(`${BASE_URL}/irisgst/topaz/api/v0.3/cewb/getcewb`, { params: req.query, headers: { Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

/* ======================================================================
   6. EWB BY DOC NUM & TYPE
   ====================================================================== */
app.get("/proxy/topaz/ewb/byDocNumType", (req, res) =>
  proxyRequest(res, () =>
    axios.get(
      `${BASE_URL}/irisgst/topaz/api/v0.3/getewb/docNumAndType`,
      {
        params: req.query,
        headers: {
          "Accept": "application/json",
          "Content-Type": "application/json", // ★ REQUIRED
          product: "TOPAZ",
          ...authHeaders(req)
        }
      }
    )
  )
);




app.post("/proxy/topaz/ewb/bulkByDocNum", (req, res) =>
  proxyRequest(res, () =>
    axios.post(
      `${BASE_URL}/irisgst/topaz/api/v0.3/getewb/docNum`,
      req.body,
      {
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
          product: "TOPAZ",
          ...authHeaders(req),
        },
      }
    )
  )
);


app.get("/proxy/topaz/ewb/bulkStatus", (req, res) =>
  proxyRequest(res, () =>
    axios.get(`${BASE_URL}/irisgst/topaz/api/v0.3/getewb/docNum/status`,
      {
        params: req.query,
        headers: {
          Accept: "application/json",
          product: "TOPAZ",
          ...authHeaders(req)
        }
      }
    )
  )
);


app.get("/proxy/topaz/ewb/bulkDownload", (req, res) =>
  proxyRequest(res, () =>
    axios.get(`${BASE_URL}/irisgst/topaz/api/v0.3/getewb/docNum/download`, { params: req.query, headers: { Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

/* ======================================================================
   7. MULTI-VEHICLE
   ====================================================================== */
app.post("/proxy/topaz/multiVehicle/initiate", (req, res) =>
  proxyRequest(res, () =>
    axios.post(`${BASE_URL}/irisgst/topaz/api/v0.3/ewb/multiVehicle`, req.body, { headers: { "Content-Type": "application/json", Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

app.get("/proxy/topaz/multiVehicle/requests", (req, res) =>
  proxyRequest(res, () =>
    axios.get(`${BASE_URL}/irisgst/topaz/api/v0.3/getewb/multiVehReq`, { params: req.query, headers: { Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

app.get("/proxy/topaz/multiVehicle/groupDetails", (req, res) =>
  proxyRequest(res, () =>
    axios.get(`${BASE_URL}/irisgst/topaz/api/v0.3/getewb/multiVehDet`, { params: req.query, headers: { Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

app.post("/proxy/topaz/multiVehicle/add", (req, res) =>
  proxyRequest(res, () =>
    axios.post(`${BASE_URL}/irisgst/topaz/api/v0.3/ewb/multiVehicle/add`, req.body, { headers: { "Content-Type": "application/json", Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

app.post("/proxy/topaz/multiVehicle/edit", (req, res) =>
  proxyRequest(res, () =>
    axios.post(`${BASE_URL}/irisgst/topaz/api/v0.3/ewb/multiVehicle/edit`, req.body, { headers: { "Content-Type": "application/json", Accept: "application/json", product: "TOPAZ", ...authHeaders(req) } })
  )
);

/* ======================================================================
   8. PRINT EWB
   ====================================================================== */
const printEWB = async (url, req, res, filename) => {
  try {
    const response = await axios.post(`${BASE_URL}${url}`, req.body, {
      headers: { Accept: "application/pdf", "Content-Type": "application/json", product: "TOPAZ", ...authHeaders(req) },
      responseType: "arraybuffer",
    });
    res.set("Content-Type", "application/pdf");
    res.set("Content-Disposition", `attachment; filename=${filename}`);
    res.send(response.data);
  } catch (err) {
    res.status(err.response?.status || 500).json(err.response?.data || { error: "Print failed" });
  }
};

app.post("/proxy/topaz/ewb/printDetails", (req, res) => printEWB("/irisgst/topaz/ewb/print/details", req, res, "ewb-details.pdf"));
app.post("/proxy/topaz/ewb/printSummary", (req, res) => printEWB("/irisgst/topaz/ewb/print/summary", req, res, "ewb-summary.pdf"));

/* ======================================================================
   9. ENTITY MANAGEMENT (ONYX)
   ====================================================================== */
// -----------------------------
// -----------------------------
                   // GET: Business Hierarchy

// =====================
// FINAL CORRECT SERVER ROUTE
app.put('/proxy/mgmt/company/business', (req, res) => {
  proxyRequest(res, () =>
    axios.put(
      `${BASE_URL}/mgmt/company/business`,
      req.body,
      {
        headers: {
          'Content-Type': 'application/json',
          Accept: 'application/json',
          product: 'TOPAZ',
          ...authHeaders(req),
        },
      }
    )
  );
});



// =====================
// Get Business Hierarchy
// =====================
app.get('/proxy/mgmt/businessHierarchy', (req, res) => {
  proxyRequest(res, () =>
    axios.get(`${BASE_URL}/mgmt/company/businesshierarchy`, {
      params: req.query,
      headers: {
        Accept: 'application/json',
        product: 'TOPAZ',
        ...authHeaders(req),
      },
    })
  );
});

// =====================
// Get Assigned Places of Business (POB)
// =====================
app.get('/proxy/mgmt/pob/list', (req, res) => {
  proxyRequest(res, () =>
    axios.get(`${BASE_URL}/mgmt/user/getAssignedPlaceOfBusinesses`, {
      params: req.query,
      headers: { Accept: 'application/json', ...authHeaders(req) },
    })
  );
});

// =====================
// Get Assigned GSTINs for Filing Business
// =====================
app.get('/proxy/mgmt/user/company/filingbusiness', (req, res) => {
  proxyRequest(res, () =>
    axios.get(`${BASE_URL}/mgmt/user/company/filingbusiness`, {
      params: req.query,
      headers: { Accept: 'application/json', ...authHeaders(req) },
    })
  );
});




/* ======================================================================
   START SERVER
   ====================================================================== */
app.listen(PORT, () => console.log(`🚀 Proxy server running on http://localhost:${PORT}`));
